@startuml
class ProductSubmissionDocument {
	string identifier
	date splVersion
	string submissionIdentifier
	positiveInt versionNumber
	CodeableConcept type
	string title 0..1
}
ProductSubmissionDocument o-- RelatedDocument
class RelatedDocument {
	string identifier
	string submissionIdentifier
	positiveInt versionNumber
}
ProductSubmissionDocument *-- Labeler
class Labeler {
	string dunsNumber
	string name
}
Labeler *-- "0..1" Registrant
class Registrant {
	string dunsNumber
	string name
}
Registrant *-- "0..*" Establishment
class Establishment {
	string dunsNumber
	string name
}
Establishment *-- "1..*" BusinessOperation
class BusinessOperation {
	CodeableConcept code
	CodeableConcept productNDC 0..1
}
ProductSubmissionDocument *-- "1..*" Section
class Section {
	string identifier
	dateTime effectiveTime
	CodeableConcept type
	string title 0..1
	xhtml text 0..1
	xhtml highlights 0..1
	MedicinalProduct product 0..*
}
Section *-- "0..*" Image
class Image {
  string title
  url reference
}
Section *-- "0..*" Section
@enduml
