id: hl7.fhir.us.spl
canonical: http://hl7.org/fhir/us/spl
name: FHIR_SPL
title: SPL Mapping FHIR Implementation Guide
description: A guide that provides mapping from the FDA SPL Documents to FHIR Resources and operations.
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: Biomedical Research and Regulatory WG
  url: http://www.hl7.org/Special/committees/rcrim/index.cfm
jurisdiction: urn:iso:std:iso:3166#US "United States of America"

pages:
  index.md:
    title: SPL Mapping Implementation Guide Home Page
  usecases.md:
    title: Use Cases and Overview
  specification.md:
    title: Formal Specification
  downloads.md:
    title: Downloads
  credits.md:
    title: Credits

menu:
  Table of Contents: toc.html
  Specification:
    Home Page: index.html
    Use Cases and Overview: usecases.html
    Formal Specification: specification.html
    Downloads: downloads.html
    Credits: credits.html
  Artifacts: artifacts.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}

groups:
  LogicalModel:
    name: Logical Models
    description: Logical models that show the data elements for each use case
    resources:
      - StructureDefinition/LabelerCodeRequestLogicalModel
      - StructureDefinition/EstablishmentRegistrationLogicalModel
      - StructureDefinition/GDUFAFacilityIdentificationLogicalModel
      - StructureDefinition/ProductSubmissionDocumentLogicalModel
  Operations:
    name: Operations
    description: Defined operations for the use cases
    resources:
      - StructureDefinition/OrganizationMessage
  LabelerRequest:
    name: FDA Labeler Organizations
    description: Artifacts associated with the Labeler Organization use cases
    resources:
      - StructureDefinition/LabelerCodeRequestBundle
      - StructureDefinition/LabelerInactivationBundle
      - StructureDefinition/LabelerCodeRequestMessage
      - StructureDefinition/LabelerInactivationMessage
      - StructureDefinition/LabelerOrganization
      - StructureDefinition/IdentifiedLabeler
      - StructureDefinition/LabelerBusinessOperation
  EstablishmentRegistration:
    name: FDA Establishment Organizations
    description: Artifacts associated with the Estabishment Organization use cases
    resources:
      - StructureDefinition/EstablishmentRegistrationBundle
      - StructureDefinition/EstablishmentInactivationBundle
      - StructureDefinition/EstablishmentRegistrationMessage
      - StructureDefinition/EstablishmentInactivationMessage
      - StructureDefinition/EstablishmentRegistrantOrganization
      - StructureDefinition/EstablishmentOrganization
      - StructureDefinition/IdentifiedEstablishmentRegistrant
      - StructureDefinition/IdentifiedEstablishment
      - StructureDefinition/EstablishmentAffiliation
      - StructureDefinition/EstablishmentBusinessOperation
  GDUFAFacility:
    name: GDUFA Facility Identification
    description: Artifacts associated with the GDUFA Facility Identification use cases
    resources:
      - StructureDefinition/GDUFAFacilityIdentificationBundle
      - StructureDefinition/GDUFAFacilityInactivationBundle
      - StructureDefinition/GDUFARegistrantOrganization
      - StructureDefinition/GDUFAFacilityOrganization
      - StructureDefinition/IdentifiedGDUFARegistrant
      - StructureDefinition/IdentifiedGDUFAFacility
      - StructureDefinition/GDUFAFacilityAffiliation
      - StructureDefinition/GDUFAFacilityBusinessOperation
  GeneralOrganization:
    name: General Organization Structures
    description: Artifacts that are used in any of the Organization use cases
    resources:
      - StructureDefinition/RegistrantOrganization
      - StructureDefinition/IdentifiedOrganization
      - StructureDefinition/USAgentOrganization
      - StructureDefinition/USAgentAffiliation
      - StructureDefinition/ImporterOrganization
      - StructureDefinition/ImporterAffiliation
  ProductSubmission:
    name: Product Submission Document
    description: Artifacts associated with the submission of a product document
    resources:
      - StructureDefinition/ProductSubmissionDocument 
  DualSubmission:
    name: Dual Submission Tracking
    description: Artifacts needed for tracking dual submissions of SPL documents and FHIR Bundles
    resources:
      - StructureDefinition/SPLDocumentReference
      - StructureDefinition/DualSubmissionProvenance
