id: hl7.fhir.us.spl
canonical: http://hl7.org/fhir/us/spl
name: FHIR_SPL
title: SPL Mapping FHIR R5 Implementation Guide
description: A guide that provides mapping from the FDA SPL Documents to FHIR Resources and operations.
status: active
version: 0.2.7
fhirVersion: 5.0.0
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: HL7 International / Biomedical Research and Regulation
  url: http://www.hl7.org/Special/committees/rcrim
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: brr 

pages:
  index.md:
    title: SPL Mapping Implementation Guide Home Page
  organization.md:
    title: Organization-Based Use Cases
  druglabel.md:
    title: Submit a Drug Label
  howtolabel.md:
    title: How to Create a FHIR Drug Label
  transforms.md:
    title: SPL / FHIR Transforms
  downloads.md:
    title: Downloads
  credits.md:
    title: Credits

menu:
  Table of Contents: toc.html
  Home Page: index.html
  Use Cases:
    Organization-Based Submissions: organization.html
    Drug Label Submission: druglabel.html
  Guidance:
    How To: howtolabel.html
    Transforms: transforms.html
  Artifacts: artifacts.html
  Appendix:
    Downloads: downloads.html
    Credits: credits.html

groups:
  LogicalModel:
    name: Logical Models
    description: Logical models that show the data elements for each use case
    resources:
      - StructureDefinition/LabelerCodeRequestLogicalModel
      - StructureDefinition/EstablishmentRegistrationLogicalModel
      - StructureDefinition/GDUFAFacilityIdentificationLogicalModel
      - StructureDefinition/ProductSubmissionDocumentLogicalModel
      - StructureDefinition/SubmittedMedicationLogicalModel
  OperationBundles:
    name: Operation Bundles
    description: Bundle profiles that are used in the various use case operations
    resources:
      - StructureDefinition/OrganizationBundle
      - StructureDefinition/LabelerCodeRequestBundle
      - StructureDefinition/LabelerInactivationBundle
      - StructureDefinition/EstablishmentRegistrationBundle
      - StructureDefinition/EstablishmentInactivationBundle
      - StructureDefinition/GDUFAFacilityIdentificationBundle
      - StructureDefinition/GDUFAFacilityInactivationBundle
      - StructureDefinition/OutOfBusinessBundle
      - StructureDefinition/NoChangeNotificationBundle
  OperationMessages:
    name: Operation Message
    description: MessageHeader profiles that are used in the various use case operations
    resources:
      - StructureDefinition/OrganizationMessage
      - StructureDefinition/LabelerCodeRequestMessage
      - StructureDefinition/LabelerInactivationMessage
      - StructureDefinition/EstablishmentRegistrationMessage
      - StructureDefinition/EstablishmentInactivationMessage
      - StructureDefinition/GDUFAFacilityIdentificationMessage
      - StructureDefinition/GDUFAFacilityInactivationMessage
      - StructureDefinition/OutOfBusinessMessage
      - StructureDefinition/NoChangeNotificationMessage
  LabelerRequest:
    name: FDA Labeler Organizations
    description: Artifacts associated with the Labeler Organization use cases
    resources:
      - StructureDefinition/LabelerOrganization
      - StructureDefinition/IdentifiedLabeler
      - StructureDefinition/LabelerBusinessOperation
  EstablishmentRegistration:
    name: FDA Establishment Organizations
    description: Artifacts associated with the Estabishment Organization use cases
    resources:
      - StructureDefinition/EstablishmentRegistrantOrganization
      - StructureDefinition/EstablishmentOrganization
      - StructureDefinition/IdentifiedEstablishmentRegistrant
      - StructureDefinition/IdentifiedEstablishment
      - StructureDefinition/EstablishmentAffiliation
      - StructureDefinition/EstablishmentBusinessOperation
  GDUFAFacility:
    name: GDUFA Facility Identification
    description: Artifacts associated with the GDUFA Facility Identification use cases
    resources:
      - StructureDefinition/GDUFARegistrantOrganization
      - StructureDefinition/GDUFAFacilityOrganization
      - StructureDefinition/IdentifiedGDUFARegistrant
      - StructureDefinition/IdentifiedGDUFAFacility
      - StructureDefinition/GDUFAFacilityAffiliation
      - StructureDefinition/GDUFAFacilityBusinessOperation
  GeneralOrganization:
    name: General Organization Structures
    description: Artifacts that are used in any of the Organization use cases
    resources:
      - StructureDefinition/RegistrantOrganization
      - StructureDefinition/IdentifiedOrganization
      - StructureDefinition/USAgentOrganization
      - StructureDefinition/LabelerUSAgentAffiliation
      - StructureDefinition/EstablishmentUSAgentAffiliation
      - StructureDefinition/ImporterOrganization
      - StructureDefinition/ImporterAffiliation
      - StructureDefinition/SPLAddress
      - StructureDefinition/SPLContactPoint
  ProductSubmission:
    name: Product Submission Content
    description: Artifacts associated with the submission of a product document
    resources:
      - StructureDefinition/ProductSubmissionBundle
      - StructureDefinition/ProductSubmissionDocument
      - StructureDefinition/sectionEffectiveTime
      - StructureDefinition/sectionLinkId
      - StructureDefinition/SubmittedMedicinalProduct
      - StructureDefinition/SubmittedMedicinalPackaging
      - StructureDefinition/packageInstanceOf
      - StructureDefinition/SubmittedManufacturedItem
      - StructureDefinition/itemMarketingStatusDates
      - StructureDefinition/SubmittedMedicinalProductIngredient
      - StructureDefinition/SubmittedIngredientDefinition
      - StructureDefinition/SubmittedMedicinalProductMarketing
  AllopurinolLabel:
    name: Allopurinol Label
    description: Example Instances associated with the label for Allopurinol USP
    resources:
      - Bundle/AllopurinolTabletLabelBundle
      - Composition/AllopurinolTabletLabelComposition
      - MedicinalProductDefinition/AllopurinolUSPDefinition
      - PackagedProductDefinition/Allopurinol30Tablets
      - PackagedProductDefinition/Allopurinol60Tablets
      - PackagedProductDefinition/Allopurinol90Tablets
      - PackagedProductDefinition/Allopurinol100Tablets
      - ManufacturedItemDefinition/AllopurinolTablet
      - Ingredient/AllopurinolUSPActiveIngredient
      - SubstanceDefinition/AllopurinolIngredientDefinition
      - Ingredient/AllopurinolUSPIngredient1
      - Ingredient/AllopurinolUSPIngredient2
      - Ingredient/AllopurinolUSPIngredient3
      - Ingredient/AllopurinolUSPIngredient4
      - Ingredient/AllopurinolUSPIngredient5
      - Ingredient/AllopurinolUSPIngredient6
      - RegulatedAuthorization/AllopurinolMarketing
      - Organization/AidarexPharmaceuticals
  EnbrelLabel:
    name: Enbrel Label
    description: Example Instances associated with the label for Enbrel
    resources:
      - Bundle/EnbrelSyringeLabelBundle
      - Composition/EnbrelSyringeLabelComposition
      - Organization/ImmunexCorporation
      - MedicinalProductDefinition/Enbrel010Definition
      - PackagedProductDefinition/Enbrel010Package
      - RegulatedAuthorization/Enbrel010Marketing
      - MedicinalProductDefinition/Enbrel021Definition
      - PackagedProductDefinition/Enbrel021Package
      - RegulatedAuthorization/Enbrel021Marketing
      - MedicinalProductDefinition/Enbrel032Definition
      - PackagedProductDefinition/Enbrel032Package
      - RegulatedAuthorization/Enbrel032Marketing
      - MedicinalProductDefinition/Enbrel044Definition
      - PackagedProductDefinition/Enbrel044Package
      - RegulatedAuthorization/Enbrel044Marketing
      - MedicinalProductDefinition/Enbrel055Definition
      - PackagedProductDefinition/Enbrel055Package
      - RegulatedAuthorization/Enbrel055Marketing
      - MedicinalProductDefinition/Enbrel435Definition
      - PackagedProductDefinition/Enbrel435Package
      - RegulatedAuthorization/Enbrel435Marketing
      - MedicinalProductDefinition/Enbrel445Definition
      - PackagedProductDefinition/Enbrel445Package
      - RegulatedAuthorization/Enbrel445Marketing
      - MedicinalProductDefinition/Enbrel446Definition
      - PackagedProductDefinition/Enbrel446Package
      - RegulatedAuthorization/Enbrel446Marketing
      - MedicinalProductDefinition/Enbrel455Definition
      - PackagedProductDefinition/Enbrel455Package
      - RegulatedAuthorization/Enbrel455Marketing
      - MedicinalProductDefinition/Enbrel456Definition
      - PackagedProductDefinition/Enbrel456Package
      - RegulatedAuthorization/Enbrel456Marketing
      - MedicinalProductDefinition/Enbrel425Definition
      - PackagedProductDefinition/Enbrel425Package
      - RegulatedAuthorization/Enbrel425Marketing
      - MedicinalProductDefinition/Enbrel425Part1Definition
      - PackagedProductDefinition/Enbrel425Part1Package
      - RegulatedAuthorization/Enbrel425Part1Marketing
      - MedicinalProductDefinition/Enbrel425Part2Definition
      - PackagedProductDefinition/Enbrel425Part2Package
      - RegulatedAuthorization/Enbrel425Part2Marketing
      - ManufacturedItemDefinition/Enbrel50mgSolution
      - Ingredient/Enbrel50mgSolutionActiveIngredient
      - SubstanceDefinition/EnbrelIngredientDefinition
      - Ingredient/Enbrel50mgSolutionIngredient1
      - Ingredient/Enbrel50mgSolutionIngredient2
      - Ingredient/Enbrel50mgSolutionIngredient3
      - ManufacturedItemDefinition/Enbrel25mgSolution
      - Ingredient/Enbrel25mgSolutionActiveIngredient
      - Ingredient/Enbrel25mgSolutionIngredient1
      - Ingredient/Enbrel25mgSolutionIngredient2
      - Ingredient/Enbrel25mgSolutionIngredient3
      - ManufacturedItemDefinition/EnbrelPowder
      - Ingredient/EnbrelPowderActiveIngredient
      - Ingredient/EnbrelPowderIngredient1
      - Ingredient/EnbrelPowderIngredient2
      - Ingredient/EnbrelPowderIngredient3
      - ManufacturedItemDefinition/EnbrelSterileSolution
      - Ingredient/EnbrelSterileSolutionIngredient1
      - Ingredient/EnbrelSterileSolutionIngredient2
  LantusLabel:
    name: Lantus Label
    description: Example Instances associated with the label for Lantus
    resources:
      - Bundle/LantusInjectionLabelBundle
      - Composition/LantusInjectionLabelComposition
      - MedicinalProductDefinition/LantusVialDefinition
      - MedicinalProductDefinition/LantusSyringeDefinition
      - PackagedProductDefinition/LantusSyringePackage
      - PackagedProductDefinition/LantusVialPackage
      - ManufacturedItemDefinition/LantusSolution
      - Ingredient/LantusActiveIngredient
      - SubstanceDefinition/LantusIngredientDefinition
      - Ingredient/LantusIngredient1
      - Ingredient/LantusIngredient2
      - Ingredient/LantusIngredient3
      - Ingredient/LantusIngredient4
      - Ingredient/LantusIngredient5
      - Ingredient/LantusIngredient6
      - Ingredient/LantusIngredient7
      - RegulatedAuthorization/LantusVialMarketing
      - RegulatedAuthorization/LantusSyringeMarketing
      - Organization/SanofiAventisUS
      - Organization/SanofiAventisDeutschland
      - Organization/SanofiAventisSRL

parameters:
  display-warnings: true