id: hl7.fhir.us.spl
canonical: http://hl7.org/fhir/us/spl
name: FHIR_SPL
title: SPL Mapping FHIR Implementation Guide
description: A guide that provides mapping from the FDA SPL Documents to FHIR Resources and operations.
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: Biomedical Research and Regulatory WG
  url: http://www.hl7.org/Special/committees/rcrim/index.cfm
jurisdiction: urn:iso:std:iso:3166#US "United States of America"

pages:
  index.md:
    title: SPL Mapping Implementation Guide Home Page
  usecases.md:
    title: Use Cases and Overview
  specification.md:
    title: Formal Specification
  downloads.md:
    title: Downloads
  credits.md:
    title: Credits

menu:
  Table of Contents: toc.html
  Specification:
    Home Page: index.html
    Use Cases and Overview: usecases.html
    Formal Specification: specification.html
    Downloads: downloads.html
    Credits: credits.html
  Artifacts: artifacts.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}

groups:
  EstablishmentRegistration:
    name: FDA Establishment Registration
    description: Artifacts associated with the Estabishment Registration use cases
    resources:
      - StructureDefinition/EstablishmentRequestBundle
      - StructureDefinition/EstablishmentOrganization
      - StructureDefinition/EstablishmentAffiliation
      - StructureDefinition/EstablishmentBusinessOperation
  LabelerRequest:
    name: FDA Labeler Code Request
    description: Artifacts associated with the Labeler Code Request use cases
    resources:
      - StructureDefinition/LabelerCodeRequestBundle
      - StructureDefinition/LabelerOrganization
      - StructureDefinition/LabelerBusinessOperation
  GDUFAFacility:
    name: GDUFA Facility Identification
    description: Artifacts associated with the GDUFA Facility Identification use cases
    resources:
      - StructureDefinition/GDUFAFacilityRequestBundle
      - StructureDefinition/GDUFAFacilityOrganization
      - StructureDefinition/GDUFAFacilityAffiliation
      - StructureDefinition/GDUFAFacilityBusinessOperation
  GeneralOrganization:
    name: General Organization Structures
    description: Artifacts that are used in any of the Organization use cases
    resources:
      - StructureDefinition/RegistrantOrganization
      - StructureDefinition/USAgentOrganization
      - StructureDefinition/USAgentAffiliation
      - StructureDefinition/ImporterOrganization
      - StructureDefinition/ImporterAffiliation
  ProductSubmission:
    name: Product Submission Document
    description: Artifacts associated with the submission of a product document
    resources:
      - StructureDefinition/ProductSubmissionDocument
 