id: hl7.fhir.us.spl
canonical: http://hl7.org/fhir/us/spl
name: FHIR_SPL
title: SPL Mapping FHIR Implementation Guide
description: A guide that provides mapping from the FDA SPL Documents to FHIR Resources and operations.
status: draft
version: 0.1.0
fhirVersion: 4.3.0
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: Biomedical Research and Regulatory WG
  url: http://www.hl7.org/Special/committees/rcrim/index.cfm
jurisdiction: urn:iso:std:iso:3166#US "United States of America"

pages:
  index.md:
    title: SPL Mapping Implementation Guide Home Page
  usecases.md:
    title: Use Cases and Overview
  specification.md:
    title: Formal Specification
  downloads.md:
    title: Downloads
  credits.md:
    title: Credits

menu:
  Table of Contents: toc.html
  Specification:
    Home Page: index.html
    Use Cases and Overview: usecases.html
    Formal Specification: specification.html
    Downloads: downloads.html
    Credits: credits.html
  Artifacts: artifacts.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}

groups:
  LogicalModel:
    name: Logical Models
    description: Logical models that show the data elements for each use case
    resources:
      - StructureDefinition/LabelerCodeRequestLogicalModel
      - StructureDefinition/EstablishmentRegistrationLogicalModel
      - StructureDefinition/GDUFAFacilityIdentificationLogicalModel
      - StructureDefinition/ProductSubmissionDocumentLogicalModel
      - StructureDefinition/SubmittedMedicationLogicalModel
  OperationBundles:
    name: Operation Bundles
    description: Bundle profiles that are used in the various use case operations
    resources:
      - StructureDefinition/OrganizationBundle
      - StructureDefinition/LabelerCodeRequestBundle
      - StructureDefinition/LabelerInactivationBundle
      - StructureDefinition/EstablishmentRegistrationBundle
      - StructureDefinition/EstablishmentInactivationBundle
      - StructureDefinition/GDUFAFacilityIdentificationBundle
      - StructureDefinition/GDUFAFacilityInactivationBundle
      - StructureDefinition/OutOfBusinessBundle
  OperationMessages:
    name: Operation Message
    description: MessageHeader profiles that are used in the various use case operations
    resources:
      - StructureDefinition/OrganizationMessage
      - StructureDefinition/LabelerCodeRequestMessage
      - StructureDefinition/LabelerInactivationMessage
      - StructureDefinition/EstablishmentRegistrationMessage
      - StructureDefinition/EstablishmentInactivationMessage
      - StructureDefinition/GDUFAFacilityIdentificationMessage
      - StructureDefinition/GDUFAFacilityInactivationMessage
      - StructureDefinition/OutOfBusinessMessage
  LabelerRequest:
    name: FDA Labeler Organizations
    description: Artifacts associated with the Labeler Organization use cases
    resources:
      - StructureDefinition/LabelerOrganization
      - StructureDefinition/IdentifiedLabeler
      - StructureDefinition/LabelerBusinessOperation
  EstablishmentRegistration:
    name: FDA Establishment Organizations
    description: Artifacts associated with the Estabishment Organization use cases
    resources:
      - StructureDefinition/EstablishmentRegistrantOrganization
      - StructureDefinition/EstablishmentOrganization
      - StructureDefinition/IdentifiedEstablishmentRegistrant
      - StructureDefinition/IdentifiedEstablishment
      - StructureDefinition/EstablishmentAffiliation
      - StructureDefinition/EstablishmentBusinessOperation
  GDUFAFacility:
    name: GDUFA Facility Identification
    description: Artifacts associated with the GDUFA Facility Identification use cases
    resources:
      - StructureDefinition/GDUFARegistrantOrganization
      - StructureDefinition/GDUFAFacilityOrganization
      - StructureDefinition/IdentifiedGDUFARegistrant
      - StructureDefinition/IdentifiedGDUFAFacility
      - StructureDefinition/GDUFAFacilityAffiliation
      - StructureDefinition/GDUFAFacilityBusinessOperation
  GeneralOrganization:
    name: General Organization Structures
    description: Artifacts that are used in any of the Organization use cases
    resources:
      - StructureDefinition/RegistrantOrganization
      - StructureDefinition/IdentifiedOrganization
      - StructureDefinition/USAgentOrganization
      - StructureDefinition/USAgentAffiliation
      - StructureDefinition/ImporterOrganization
      - StructureDefinition/ImporterAffiliation
      - StructureDefinition/SPLAddress
      - StructureDefinition/SPLContactPoint
  ProductSubmission:
    name: Product Submission Document
    description: Artifacts associated with the submission of a product document
    resources:
      - StructureDefinition/ProductSubmissionBundle
      - StructureDefinition/ProductSubmissionDocument
      - StructureDefinition/sectionEffectiveTime
      - StructureDefinition/versionNumber
      - StructureDefinition/sectionHighlights
  DualSubmission:
    name: Dual Submission Tracking
    description: Artifacts needed for tracking dual submissions of SPL documents and FHIR Bundles
    resources:
      - StructureDefinition/SPLDocumentReference
      - StructureDefinition/DualSubmissionProvenance
      - StructureDefinition/splDocumentDate
  AllopurinolLabel:
    name: Allopurinol Label
    description: Example Instances associated with the label for Allopurinol USP
    resources:
      - Bundle/AllopurinolTabletLabelBundle
      - Composition/AllopurinolTabletLabelComposition
      - MedicinalProductDefinition/AllopurinolUSPDefinition
      - PackagedProductDefinition/Allopurinol30Tablets
      - PackagedProductDefinition/Allopurinol60Tablets
      - PackagedProductDefinition/Allopurinol90Tablets
      - PackagedProductDefinition/Allopurinol100Tablets
      - Ingredient/AllopurinolUSPActiveIngredient
      - SubstanceDefinition/AllopurinolIngredientDefinition
      - Ingredient/AllopurinolUSPIngredient1
      - Ingredient/AllopurinolUSPIngredient2
      - Ingredient/AllopurinolUSPIngredient3
      - Ingredient/AllopurinolUSPIngredient4
      - Ingredient/AllopurinolUSPIngredient5
      - Ingredient/AllopurinolUSPIngredient6
      - RegulatedAuthorization/AllopurinolMarketing
      - Organization/AidarexPharmaceuticals
  EnbrelLabel:
    name: Enbrel Label
    description: Example Instances associated with the label for Enbrel
    resources:
      - Bundle/EnbrelSyringeLabelBundle
      - Composition/EnbrelSyringeLabelComposition
      - Organization/ImmunexCorporation
      - MedicinalProductDefinition/Enbrel010Definition
      - PackagedProductDefinition/Enbrel010Package
      - Ingredient/Enbrel010ActiveIngredient
      - SubstanceDefinition/Enbrel010IngredientDefinition
      - Ingredient/Enbrel010Ingredient1
      - Ingredient/Enbrel010Ingredient2
      - Ingredient/Enbrel010Ingredient3
      - RegulatedAuthorization/Enbrel010Marketing
      - MedicinalProductDefinition/Enbrel021Definition
      - PackagedProductDefinition/Enbrel021Package
      - Ingredient/Enbrel021ActiveIngredient
      - SubstanceDefinition/Enbrel021IngredientDefinition
      - Ingredient/Enbrel021Ingredient1
      - Ingredient/Enbrel021Ingredient2
      - Ingredient/Enbrel021Ingredient3
      - RegulatedAuthorization/Enbrel021Marketing
      - MedicinalProductDefinition/Enbrel032Definition
      - PackagedProductDefinition/Enbrel032Package
      - Ingredient/Enbrel032ActiveIngredient
      - SubstanceDefinition/Enbrel032IngredientDefinition
      - Ingredient/Enbrel032Ingredient1
      - Ingredient/Enbrel032Ingredient2
      - Ingredient/Enbrel032Ingredient3
      - RegulatedAuthorization/Enbrel032Marketing
      - MedicinalProductDefinition/Enbrel044Definition
      - PackagedProductDefinition/Enbrel044Package
      - Ingredient/Enbrel044ActiveIngredient
      - SubstanceDefinition/Enbrel044IngredientDefinition
      - Ingredient/Enbrel044Ingredient1
      - Ingredient/Enbrel044Ingredient2
      - Ingredient/Enbrel044Ingredient3
      - RegulatedAuthorization/Enbrel044Marketing
      - MedicinalProductDefinition/Enbrel055Definition
      - PackagedProductDefinition/Enbrel055Package
      - Ingredient/Enbrel055ActiveIngredient
      - SubstanceDefinition/Enbrel055IngredientDefinition
      - Ingredient/Enbrel055Ingredient1
      - Ingredient/Enbrel055Ingredient2
      - Ingredient/Enbrel055Ingredient3
      - RegulatedAuthorization/Enbrel055Marketing
      - MedicinalProductDefinition/Enbrel435Definition
      - PackagedProductDefinition/Enbrel435Package
      - Ingredient/Enbrel435ActiveIngredient
      - SubstanceDefinition/Enbrel435IngredientDefinition
      - Ingredient/Enbrel435Ingredient1
      - Ingredient/Enbrel435Ingredient2
      - Ingredient/Enbrel435Ingredient3
      - RegulatedAuthorization/Enbrel435Marketing
      - MedicinalProductDefinition/Enbrel445Definition
      - PackagedProductDefinition/Enbrel445Package
      - Ingredient/Enbrel445ActiveIngredient
      - SubstanceDefinition/Enbrel445IngredientDefinition
      - Ingredient/Enbrel445Ingredient1
      - Ingredient/Enbrel445Ingredient2
      - Ingredient/Enbrel445Ingredient3
      - RegulatedAuthorization/Enbrel445Marketing
      - MedicinalProductDefinition/Enbrel446Definition
      - PackagedProductDefinition/Enbrel446Package
      - Ingredient/Enbrel446ActiveIngredient
      - SubstanceDefinition/Enbrel446IngredientDefinition
      - Ingredient/Enbrel446Ingredient1
      - Ingredient/Enbrel446Ingredient2
      - Ingredient/Enbrel446Ingredient3
      - RegulatedAuthorization/Enbrel446Marketing
      - MedicinalProductDefinition/Enbrel455Definition
      - PackagedProductDefinition/Enbrel455Package
      - Ingredient/Enbrel455ActiveIngredient
      - SubstanceDefinition/Enbrel455IngredientDefinition
      - Ingredient/Enbrel455Ingredient1
      - Ingredient/Enbrel455Ingredient2
      - Ingredient/Enbrel455Ingredient3
      - RegulatedAuthorization/Enbrel455Marketing
      - MedicinalProductDefinition/Enbrel456Definition
      - PackagedProductDefinition/Enbrel456Package
      - Ingredient/Enbrel456ActiveIngredient
      - SubstanceDefinition/Enbrel456IngredientDefinition
      - Ingredient/Enbrel456Ingredient1
      - Ingredient/Enbrel456Ingredient2
      - Ingredient/Enbrel456Ingredient3
      - RegulatedAuthorization/Enbrel456Marketing
      - MedicinalProductDefinition/Enbrel425Definition
      - PackagedProductDefinition/Enbrel425Package
      - RegulatedAuthorization/Enbrel425Marketing
      - MedicinalProductDefinition/Enbrel425Part1Definition
      - PackagedProductDefinition/Enbrel425Part1Package
      - RegulatedAuthorization/Enbrel425Part1Marketing
      - MedicinalProductDefinition/Enbrel425Part2Definition
      - PackagedProductDefinition/Enbrel425Part2Package
      - RegulatedAuthorization/Enbrel425Part2Marketing
      - Ingredient/Enbrel425Part1ActiveIngredient
      - SubstanceDefinition/Enbrel425Part1IngredientDefinition
      - Ingredient/Enbrel425Part1Ingredient1
      - Ingredient/Enbrel425Part1Ingredient2
      - Ingredient/Enbrel425Part1Ingredient3
      - Ingredient/Enbrel425Part2Ingredient1
      - Ingredient/Enbrel425Part2Ingredient2
  LantusLabel:
    name: Lantus Label
    description: Example Instances associated with the label for Lantus
    resources:
      - Bundle/LantusInjectionLabelBundle
      - Composition/LantusInjectionLabelComposition
      - MedicinalProductDefinition/LantusVialDefinition
      - MedicinalProductDefinition/LantusSyringeDefinition
      - PackagedProductDefinition/LantusVialPackage
      - PackagedProductDefinition/LantusSyringePackage
      - Ingredient/LantusVialActiveIngredient
      - SubstanceDefinition/LantusVialIngredientDefinition
      - Ingredient/LantusVialIngredient1
      - Ingredient/LantusVialIngredient2
      - Ingredient/LantusVialIngredient3
      - Ingredient/LantusVialIngredient4
      - Ingredient/LantusVialIngredient5
      - Ingredient/LantusVialIngredient6
      - Ingredient/LantusVialIngredient7
      - Ingredient/LantusSyringeActiveIngredient
      - SubstanceDefinition/LantusSyringeIngredientDefinition
      - Ingredient/LantusSyringeIngredient1
      - Ingredient/LantusSyringeIngredient2
      - Ingredient/LantusSyringeIngredient3
      - Ingredient/LantusSyringeIngredient4
      - Ingredient/LantusSyringeIngredient5
      - Ingredient/LantusSyringeIngredient6
      - RegulatedAuthorization/LantusVialMarketing
      - RegulatedAuthorization/LantusSyringeMarketing
      - Organization/SanofiAventisUS
      - Organization/SanofiAventisDeutschland
      - Organization/SanofiAventisSRL
