<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2022r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="xs fn">
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:param name="documentIdentifier" as="xs:string" required="yes"/>
	<xsl:param name="splDate" as="xs:date" required="yes"/>
	<xsl:param name="setIdentifier" as="xs:string" required="yes"/>
	<xsl:param name="version" as="xs:string" required="yes"/>
	<xsl:template match="/">
		<xsl:processing-instruction name="{'xml-stylesheet'}" select="'href=&quot;https://www.accessdata.fda.gov/spl/stylesheet/spl.xsl&quot; type=&quot;text/xml&quot;'"/>
		<document xmlns="urn:hl7-org:v3">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'urn:hl7-org:v3 https://www.accessdata.fda.gov/spl/schema/spl.xsd'"/>
			<id>
				<xsl:attribute name="root" namespace="" select="$documentIdentifier"/>
			</id>
			<code>
				<xsl:attribute name="code" namespace="" select="'69968-6'"/>
				<xsl:attribute name="codeSystem" namespace="" select="'2.16.840.1.113883.6.1'"/>
				<xsl:attribute name="displayName" namespace="" select="'NDC LABELER CODE INACTIVATION'"/>
			</code>
			<effectiveTime>
				<xsl:attribute name="value" namespace="" select="format-date($splDate, '[Y][M,2][D,2]', 'en', (), ())"/>
			</effectiveTime>
			<setId>
				<xsl:attribute name="root" namespace="" select="$setIdentifier"/>
			</setId>
			<versionNumber>
				<xsl:attribute name="value" namespace="" select="$version"/>
			</versionNumber>
			<component>
				<structuredBody>
					<xsl:sequence select="()"/>
				</structuredBody>
			</component>
		</document>
	</xsl:template>
</xsl:stylesheet>
