<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2022r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="xs fn">
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:param name="dunsNumber" as="xs:string" required="yes"/>
	<xsl:param name="labelerName" as="xs:string" required="yes"/>
	<xsl:template match="/">
		<Bundle xmlns="http://hl7.org/fhir" xmlns:xhtml="http://www.w3.org/1999/xhtml">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'http://hl7.org/fhir file:///Z:/Documents/DDIWork/Samvit/SPL/SPLtoFHIR/mapforce/fhir-single.xsd'"/>
			<type>
				<xsl:attribute name="value" namespace="" select="'message'"/>
			</type>
			<timestamp>
				<xsl:attribute name="value" namespace="" select="xs:string(fn:current-dateTime())"/>
			</timestamp>
			<entry>
				<fullUrl>
					<xsl:attribute name="value" namespace="" select="xs:string(xs:anyURI('http://example.org/MessageHeader/LabelerInactivationMessage'))"/>
				</fullUrl>
				<xsl:variable name="var1_create_MessageHeader" as="node()">
					<MessageHeader>
						<id>
							<xsl:attribute name="value" namespace="" select="'LabelerInactivationMessage'"/>
						</id>
						<eventCoding>
							<system>
								<xsl:attribute name="value" namespace="" select="xs:string(xs:anyURI('http://loinc.org'))"/>
							</system>
							<code>
								<xsl:attribute name="value" namespace="" select="'69968-6'"/>
							</code>
						</eventCoding>
						<source>
							<endpointUrl>
								<xsl:attribute name="value" namespace="" select="xs:string(xs:anyURI('http://example.org'))"/>
							</endpointUrl>
						</source>
						<focus>
							<reference>
								<xsl:attribute name="value" namespace="" select="'Organization/IdentifiedLabelerOrganization'"/>
							</reference>
						</focus>
					</MessageHeader>
				</xsl:variable>
				<resource>
					<MessageHeader>
						<xsl:sequence select="($var1_create_MessageHeader/@node(), $var1_create_MessageHeader/node())"/>
					</MessageHeader>
				</resource>
			</entry>
			<entry>
				<fullUrl>
					<xsl:attribute name="value" namespace="" select="xs:string(xs:anyURI('http://example.org/Organization/IdentifiedLabelerOrganization'))"/>
				</fullUrl>
				<xsl:variable name="var2_create_Organization" as="node()">
					<Organization>
						<id>
							<xsl:attribute name="value" namespace="" select="'IdentifiedLabelerOrganization'"/>
						</id>
						<identifier>
							<system>
								<xsl:attribute name="value" namespace="" select="xs:string(xs:anyURI('http://terminology.hl7.org/NamingSystem/DUNSNumber'))"/>
							</system>
							<value>
								<xsl:attribute name="value" namespace="" select="$dunsNumber"/>
							</value>
						</identifier>
						<type>
							<coding>
								<system>
									<xsl:attribute name="value" namespace="" select="xs:string(xs:anyURI('http://hl7.org/fhir/us/spl/CodeSystem/codesystem-organizationTypes'))"/>
								</system>
								<code>
									<xsl:attribute name="value" namespace="" select="'Labeler'"/>
								</code>
							</coding>
						</type>
						<name>
							<xsl:attribute name="value" namespace="" select="$labelerName"/>
						</name>
					</Organization>
				</xsl:variable>
				<resource>
					<Organization>
						<xsl:sequence select="($var2_create_Organization/@node(), $var2_create_Organization/node())"/>
					</Organization>
				</resource>
			</entry>
		</Bundle>
	</xsl:template>
</xsl:stylesheet>
